### ISSUE TITLE
PLEASE GIVE THE CIRCUIT OF THE MODEL PLS

### ISSUE THREAD

**Issue by Sorish7128J** [rv2442/light-based-image-transmission#1]
PLEASE GIVE THE CIRCUIT OF THE MODEL PLS

**Comment by rv2442** [comment]
Please refer this:
https://projecthub.arduino.cc/saadsaif0333/data-transfer-using-led-light-li-fi-ee33a3

**Comment by rv2442** [comment]
With this I believe the Issue has been resolved hence I am closing this Issue
